"""empty message

Revision ID: e98d8e08a9d0
Revises: fb9f86493152
Create Date: 2018-09-02 05:41:05.131934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98d8e08a9d0'
down_revision = 'fb9f86493152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_name_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_name_key', 'items', ['name'])
    # ### end Alembic commands ###
